services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    volumes:
      - devdb_data:/var/lib/postgresql/data
    networks:
      - dev-network
  dev-redis:
    image: redis:8.4-rc1-alpine3.22
    ports:
      - "6379:6379"
    networks:
      - dev-network
    volumes:
      - redis_data:/data
  dev-rabbitmq:
    image: rabbitmq:4.2.1-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dev-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

networks:
  dev-network:

volumes:
  devdb_data:
  redis_data:
  rabbitmq_data:
